[general]
base_aspect_ratio = 1.77 # 16:9
screen_height = 140.0
scroll_speed = 5.0

[paths]
tiles_path = "tiles.png"
planes_path = "player_ship_loop.png.png"
background_path = "background_0.png"

[sprites]
sprite_scale = 1.0
tile_size = 16.0
tile_padding = 1.0

[player]
base_health = 100
movement_speed = 1700.0
max_speed = 500.0

[animations]
default_frame_duration = 0.2
explosion_frame_duratioon = 0.1

